### PR TITLE
Add ESLint support to React templates

### LINKED ISSUE #11: Add ESLint support to React template
Just as #9, React template needs ESLint support out of the box.

It has the `.eslintrc` file ok, but it's simply unused without the `eslint` packages. And, of course, like in the mentionated issue, the generated `package.json` contains:

```json
  "lint": "echo \"No linting configured\""
```

Most peculiar thing about this?

The default "Vanilla ES6/7" template, that *doesn't need* it, installs the `devDependencies` that the React template *needs and don't have*. Just copy pasted from a generated "Vanilla ES6/7" `package.json`:

```json
"devDependencies": {
        "babel-plugin-transform-async-to-generator": "^6.22.0",
        "babel-preset-env": "^1.1.8",
        "babel-preset-react": "^6.23.0",
        "electron-prebuilt-compile": "1.4.15",
        "eslint": "^3.15.0",
        "eslint-config-airbnb": "^14.1.0",
        "eslint-plugin-import": "^2.2.0",
        "eslint-plugin-jsx-a11y": "^4.0.0",
        "eslint-plugin-react": "^6.10.0"
   }
```

These two last dependencies get unused in a vanilla ES6/7 project.

I think this happens just because `eslint-config-airbnb` shouldn't be used in "Vanilla ES6/7". Why? Because what you just saw: it includes config about React.

There are two `eslint-config-whatever` official npm packages available for enforcing `airbnb` coding style:

1. [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). Includes everything: vanilla ES6+ React.
2. [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base). Includes only vanilla ES6.

So "Vanilla ES6/7" template ends having these extra packages it doesn't need and doesn't use: this only makes the download bigger. And "React" template ends not having these extra packages it needs for linting and with linting not out-the-box because the linting it need it's going to "Vanilla ES6/7" :(.

If there is a "React" template, this template should be the one having the React-related stuff.

I took a brief look to all the files here, thinking about to make a PR, but I'm a bit lost about all the importing and etc. I didn't get where are coming all the imported pieces in that time, so better leave it here to someone more close to it ñ_ñ.

Apart from the proper packages, I think the other only needed change is with the `lint` npm script (and adding `.eslintcache` to `.gitignore`):

```json
  "lint": "eslint --cache --ext .jsx,.js src"
```

Would suffice. At least, I think so: for now, it lints.

### PR DESCRIPTION
**Pull request by soulchainer**
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge-templates/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* [x] The changes have sufficient test coverage (if applicable).
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes**

Basically I did what I commented on #11 , some time ago, that should be done to solve this.  That is:

1. Add the proper ESLint packages for linting React. Like airbnb packages are being used in base template (as I commented in #11), this means all the packages needed by `eslint-config-airbnb`, which includes React ones.
2. As a side effect of doing `npm test`, there was added a `package-lock.json` files to each template folder. This is a thing that `npm` does now automatically, like `yarn` with the `yarn.lock`. Usually this files are versioned, so... If they need to be deleted, just tell me (then this should be added to the global `.gitignore`).
3. Edited the `lint` npm script generated when we create a project with this template, to use ESLint properly.
4. Add `.eslintcache` to the `.gitignore`generated to each project created using this template. This file is created by the `--cache` option of ESLint. Using this option, ESLint only checks the changed files, not everything every time.
5. The minor formatting change on `react/tmpl/src/index.js` is because ESLint rules demanded it, so... :þ.

Fixes #11.

### CODE REVIEW

**Comment by malept** [comment]
@MarshallOfSound what should our policy be on lock files? It seems to me that we'd either have to have both Yarn and NPM lock files, or neither.

**Comment by MarshallOfSound** [comment]
@malept I believe neither

**Comment by malept** [comment]
Agreed. @soulchainer can you drop the package-lock.json files?

**Comment by soulchainer** [comment]
@malept Done ;). And added `package-lock.json` to `.gitignore`, as I said previously, because these files are generated every time you run `npm test` on the project with the newest `npm` versions.

**Review by malept — APPROVED** [review]

**Pull request merged**
